name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Change to article-viewer directory
        run: cd article-viewer
      
      - name: Install dependencies
        run: npm ci
        working-directory: article-viewer
      
      - name: Build project
        run: npm run build
        working-directory: article-viewer
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: article-viewer/dist
